#!/bin/sh

# Versioning
.git
.hg
.lock-wscript
.svn
.wafpickle-*
CVS

# Testing
.travis.yml
/test

# Other files
.*.swp
._*
.DS_Store
config.gypi
.npmrc

# Log files
npm-debug.log

# don't ignore .npmignore files
# these are used in some tests.
!.npmignore


# Projects
/build
/release
/node_modules
/tmp
/temp
