#!/bin/sh

# Source Prezto by Sorin Ionescu <sorin.ionescu@gmail.com>
if [[ -s "${ZDOTDIR:-$HOME}/.dotfiles/zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.dotfiles/zprezto/init.zsh"
fi

# Customize to your needs...